apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: users
    version: v1
  name: users-deployment
  namespace: diary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - image: rasouza/diary-users
        name: users
        ports:
          - containerPort: 8000
        envFrom:
        - configMapRef:
            name: users-config
        - secretRef:
            name: users-secret
  revisionHistoryLimit: 0