apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base/

commonLabels:
  app: users

namespace: diary

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml

images:
- name: rasouza/diary-users
  newTag: d3b1bcc

configMapGenerator:
  - name: users-config
    envs: 
    - envs/app.env

secretGenerator:
  - name: users-secret
    type: "Opaque"
    envs:
    - envs/db.env
    - envs/credentials.env
