apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: users

namespace: diary

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml

images:
- name: rasouza/diary-users
  newTag: d3b1bcc

configMapGenerator:
  - name: users-config
    envs: 
    - envs/app.env
    - envs/urls.env

secretGenerator:
  - name: users-secret
    type: "Opaque"
    envs:
    - envs/db.env
    - envs/credentials.env

vars:
  - name: MY_SERVICE_NAME
    objref:
      kind: Service
      name: users-svc
      apiVersion: v1
