commonLabels:
  app: users

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml
- configmap.yaml
- secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rasouza/diary-users
  newTag: e8a2bb5
