commonLabels:
  app: users

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rasouza/diary-users
  newTag: 69f6c2e
