apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users-virtual-svc
  namespace: diary
spec:
  hosts:
    - users.diary.local
  gateways:
    - ingressgateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: users
        port:
          number: 8000
---