apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diary
  name:  idp-deployment
  labels:
    app:  idp
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  idp
        version: v1
    spec:
      initContainers:
      - image: oryd/hydra:v1.4.5
        name: idp-migrate
        command: ["hydra", "migrate", "sql", "-e", "--yes"]
        envFrom:
        - secretRef:
            name: idp-secret
        env:
        - name: DSN
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)?search_path=$(DB_SCHEMA)"  
      containers:    
      - image:  oryd/hydra:v1.4.5
        name:  idp
        command:
        - hydra
        - serve
        - all
        - --dangerous-force-http
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 4444
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4444
        env:
        - name: DSN
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)?search_path=$(DB_SCHEMA)"
        - name: URLS_SELF_ISSUER
          value: $(IDP_EXTERNAL_URL)
        - name: URLS_CONSENT
          value: $(USERS_URL)/consent
        - name: URLS_LOGIN
          value: $(FRONTEND_URL)/auth/login
        - name: URLS_LOGIN
          value: $(FRONTEND_URL)/auth/logout
        - name: OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES
          value: public/pairwise
        envFrom:
        - configMapRef:
            name: idp-config
        - secretRef:
            name: idp-secret
        ports:
        - containerPort:  4444
          name:  public
        - containerPort: 4445
          name: admin
  revisionHistoryLimit: 0
