apiVersion: batch/v1
kind: Job
metadata:
  name:  idp-migrate
  namespace: diary
spec:
  # ttlSecondsAfterFinished: 100
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: idp-migrate
        image: oryd/hydra:v1.4.5
        command: ["hydra", "migrate", "sql", "-e", "--yes"]
        env:
        - name: DSN
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)?search_path=$(DB_SCHEMA)"
        envFrom:
        - configMapRef:
            name: idp-config
        - secretRef:
            name: idp-secret
