apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: idp

namespace: diary

resources:
- deployment.yaml
- service.yaml
- virtualsvc.yaml

configMapGenerator:
  - name: idp-config
    envs: 
    - envs/urls.env

secretGenerator:
  - name: idp-secret
    type: Opaque
    envs:
      - envs/db.env
      - envs/secrets.env