---
# Source: postgresql/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: db-postgresql-metrics
  labels:
    app: postgresql
    chart: postgresql-8.9.0
    release: "db"
    heritage: "Helm"
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9187
      targetPort: http-metrics
  selector:
    app: postgresql
    release: db
    role: master
