apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    version: v1
  name: frontend-deployment
  namespace: diary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - image: rasouza/diary-frontend
        name: frontend
        ports:
        - containerPort: 8000
      restartPolicy: Always
  revisionHistoryLimit: 0