apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgres

resources:
- namespace.yaml
- secret.yaml
- metrics-svc.yaml
- svc-headless.yaml
- svc.yaml
- statefulset.yaml
- servicemonitor.yaml